// नमूना डेटा — विकास और प्रदर्शन के लिए
export const SAMPLE_CATEGORIES = [
  { name: 'राजनीति', color: '#dc2626', icon: 'FiFlag', description: 'राजनीतिक समाचार और विश्लेषण' },
  { name: 'तकनीक', color: '#3B82F6', icon: 'FiCpu', description: 'तकनीकी खबरें और नवाचार' },
  { name: 'व्यापार', color: '#10B981', icon: 'FiBriefcase', description: 'व्यापार और वित्त समाचार' },
  { name: 'विज्ञान', color: '#8B5CF6', icon: 'FiZap', description: 'वैज्ञानिक खोजें' },
  { name: 'खेल', color: '#F59E0B', icon: 'FiActivity', description: 'खेल और एथलेटिक्स' },
  { name: 'मनोरंजन', color: '#EC4899', icon: 'FiStar', description: 'मनोरंजन और पॉप संस्कृति' },
  { name: 'स्वास्थ्य', color: '#06B6D4', icon: 'FiHeart', description: 'स्वास्थ्य और तंदुरुस्ती' },
  { name: 'विश्व', color: '#6366F1', icon: 'FiGlobe', description: 'अंतर्राष्ट्रीय समाचार' },
];

export const BREAKING_NEWS = [
  'ब्रेकिंग: जलवायु सम्मेलन में कार्बन उत्सर्जन पर ऐतिहासिक समझौता हुआ',
  'शेयर बाजार में जबरदस्त तेजी, सेंसेक्स नई ऊंचाई पर पहुंचा',
  'वैज्ञानिकों ने कैंसर उपचार में संभावित सफलता का दावा किया',
  'संयुक्त राष्ट्र सुरक्षा परिषद की आपातकालीन बैठक बुलाई गई',
  'टेक कंपनी ने AI-संचालित स्मार्टफोन की घोषणा की',
  'भारत ने चंद्रमा मिशन की नई तिथि घोषित की',
  'विश्व स्वास्थ्य संगठन ने नई स्वास्थ्य गाइडलाइन जारी की',
];

export const SAMPLE_ARTICLES = [
  {
    title: 'विश्व नेताओं ने COP30 शिखर सम्मेलन में ऐतिहासिक जलवायु समझौते पर हस्ताक्षर किए',
    excerpt: '195 देशों के विश्व नेताओं ने 2040 तक शून्य-उत्सर्जन की प्रतिज्ञा करते हुए एक ऐतिहासिक जलवायु समझौते पर हस्ताक्षर किए।',
    coverImage: 'https://images.unsplash.com/photo-1569163139394-de4e5f43e5ca?w=800',
    readingTime: 5,
    views: 12450,
    publishedAt: new Date(Date.now() - 1000 * 60 * 30),
    isBreaking: true,
    isFeatured: true,
    slug: 'sample-1',
    author: { name: 'सारा जॉनसन', username: 'sarahjohnson', avatar: '' },
    category: { name: 'विश्व', slug: 'world', color: '#6366F1' },
    tags: ['जलवायु', 'cop30', 'पर्यावरण'],
  },
  {
    title: 'Apple ने 72 घंटे की बैटरी वाले क्रांतिकारी AI MacBook का अनावरण किया',
    excerpt: 'नए MacBook में एक कस्टम न्यूरल प्रोसेसिंग यूनिट है जो अभूतपूर्व प्रदर्शन देती है।',
    coverImage: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800',
    readingTime: 3,
    views: 8920,
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 2),
    isTrending: true,
    slug: 'sample-2',
    author: { name: 'माइक चेन', username: 'mikechen', avatar: '' },
    category: { name: 'तकनीक', slug: 'technology', color: '#3B82F6' },
    tags: ['Apple', 'MacBook', 'AI', 'तकनीक'],
  },
  {
    title: 'फेडरल रिजर्व ने ब्याज दर कटौती के संकेत दिए, महंगाई 2 साल के निचले स्तर पर',
    excerpt: 'फेड अध्यक्ष ने आगामी बैठकों में संभावित दर कटौती का संकेत दिया।',
    coverImage: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800',
    readingTime: 4,
    views: 6750,
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 4),
    slug: 'sample-3',
    author: { name: 'एम्मा डेविस', username: 'emmadavis', avatar: '' },
    category: { name: 'व्यापार', slug: 'business', color: '#10B981' },
    tags: ['अर्थव्यवस्था', 'फेड', 'ब्याज दर'],
  },
  {
    title: 'वैज्ञानिकों ने जेम्स वेब टेलिस्कोप से 12 प्रकाश-वर्ष दूर पृथ्वी जैसा ग्रह खोजा',
    excerpt: 'खगोलविदों ने जेम्स वेब टेलिस्कोप का उपयोग करके एक ग्रह की पहचान की जिसमें मजबूत बायोसिग्नेचर हैं।',
    coverImage: 'https://images.unsplash.com/photo-1446776653964-20c1d3a81b06?w=800',
    readingTime: 6,
    views: 15320,
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 6),
    isFeatured: true,
    slug: 'sample-4',
    author: { name: 'अलेक्स टर्नर', username: 'alexturner', avatar: '' },
    category: { name: 'विज्ञान', slug: 'science', color: '#8B5CF6' },
    tags: ['अंतरिक्ष', 'विज्ञान', 'खगोलशास्त्र'],
  },
  {
    title: 'चैंपियंस लीग फाइनल: रियल मैड्रिड बनाम मैनचेस्टर सिटी का पूर्वावलोकन',
    excerpt: 'दशकों में सबसे प्रत्याशित फुटबॉल फाइनल के लिए दोनों टीमें तैयार हैं।',
    coverImage: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=800',
    readingTime: 3,
    views: 9840,
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 8),
    isTrending: true,
    slug: 'sample-5',
    author: { name: 'लिसा पार्क', username: 'lisapark', avatar: '' },
    category: { name: 'खेल', slug: 'sports', color: '#F59E0B' },
    tags: ['फुटबॉल', 'चैंपियंस लीग', 'खेल'],
  },
  {
    title: 'नए अध्ययन से पता चला: भूमध्यसागरीय आहार से हृदय रोग का खतरा 30% कम होता है',
    excerpt: 'न्यू इंग्लैंड जर्नल ऑफ मेडिसिन में प्रकाशित 10 साल के व्यापक अध्ययन ने लाभों की पुष्टि की।',
    coverImage: 'https://images.unsplash.com/photo-1498837167922-ddd27525d352?w=800',
    readingTime: 4,
    views: 5210,
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 10),
    slug: 'sample-6',
    author: { name: 'टॉम ब्राउन', username: 'tombrown', avatar: '' },
    category: { name: 'स्वास्थ्य', slug: 'health', color: '#06B6D4' },
    tags: ['स्वास्थ्य', 'आहार', 'हृदय'],
  },
];
